2022/12/28 18:14:41 [notice] 1#1: using the "epoll" event method
2022/12/28 18:14:41 [notice] 1#1: nginx/1.23.3
2022/12/28 18:14:41 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:14:41 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:14:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:14:41 [notice] 1#1: start worker processes
2022/12/28 18:14:41 [notice] 1#1: start worker process 29
2022/12/28 18:14:41 [notice] 1#1: start worker process 30
2022/12/28 18:14:41 [notice] 1#1: start worker process 31
2022/12/28 18:14:41 [notice] 1#1: start worker process 32
2022/12/28 18:14:41 [notice] 1#1: start worker process 33
2022/12/28 18:14:41 [notice] 1#1: start worker process 34
2022/12/28 18:14:41 [notice] 1#1: start worker process 35
2022/12/28 18:14:41 [notice] 1#1: start worker process 36
2022/12/28 18:14:52 [error] 30#30: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:22:34 [error] 31#31: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:24:52 [error] 33#33: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:25:15 [error] 33#33: *5 open() "/var/www/html/qe" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /qe HTTP/1.1", host: "localhost"
2022/12/28 18:25:17 [error] 33#33: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:25:53 [error] 33#33: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:23 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:26:23 [notice] 29#29: gracefully shutting down
2022/12/28 18:26:23 [notice] 32#32: gracefully shutting down
2022/12/28 18:26:23 [notice] 34#34: gracefully shutting down
2022/12/28 18:26:23 [notice] 31#31: gracefully shutting down
2022/12/28 18:26:23 [notice] 30#30: gracefully shutting down
2022/12/28 18:26:23 [notice] 36#36: gracefully shutting down
2022/12/28 18:26:23 [notice] 29#29: exiting
2022/12/28 18:26:23 [notice] 32#32: exiting
2022/12/28 18:26:23 [notice] 34#34: exiting
2022/12/28 18:26:23 [notice] 31#31: exiting
2022/12/28 18:26:23 [notice] 30#30: exiting
2022/12/28 18:26:23 [notice] 36#36: exiting
2022/12/28 18:26:23 [notice] 29#29: exit
2022/12/28 18:26:23 [notice] 34#34: exit
2022/12/28 18:26:23 [notice] 30#30: exit
2022/12/28 18:26:23 [notice] 31#31: exit
2022/12/28 18:26:23 [notice] 32#32: exit
2022/12/28 18:26:23 [notice] 36#36: exit
2022/12/28 18:26:23 [notice] 33#33: gracefully shutting down
2022/12/28 18:26:23 [notice] 35#35: gracefully shutting down
2022/12/28 18:26:23 [notice] 35#35: exiting
2022/12/28 18:26:23 [notice] 33#33: exiting
2022/12/28 18:26:23 [notice] 35#35: exit
2022/12/28 18:26:23 [notice] 33#33: exit
2022/12/28 18:26:23 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:26:23 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:26:23 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:26:23 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:26:23 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:26:23 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:26:23 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:26:23 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:26:23 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 18:26:23 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:26:23 [notice] 1#1: exit
2022/12/28 18:26:26 [notice] 1#1: using the "epoll" event method
2022/12/28 18:26:26 [notice] 1#1: nginx/1.23.3
2022/12/28 18:26:26 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:26:26 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:26:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:26:26 [notice] 1#1: start worker processes
2022/12/28 18:26:26 [notice] 1#1: start worker process 29
2022/12/28 18:26:26 [notice] 1#1: start worker process 30
2022/12/28 18:26:26 [notice] 1#1: start worker process 31
2022/12/28 18:26:26 [notice] 1#1: start worker process 32
2022/12/28 18:26:26 [notice] 1#1: start worker process 33
2022/12/28 18:26:26 [notice] 1#1: start worker process 34
2022/12/28 18:26:26 [notice] 1#1: start worker process 35
2022/12/28 18:26:26 [notice] 1#1: start worker process 36
2022/12/28 18:26:28 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:29 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:31 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:26:33 [error] 29#29: *1 open() "/var/www/html/asdasd" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /asdasd HTTP/1.1", host: "localhost"
2022/12/28 18:26:35 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:38 [error] 29#29: *1 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:26:39 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:52 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:54 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:26:57 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:26:59 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:28:00 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:28:00 [notice] 29#29: gracefully shutting down
2022/12/28 18:28:00 [notice] 31#31: gracefully shutting down
2022/12/28 18:28:00 [notice] 30#30: gracefully shutting down
2022/12/28 18:28:00 [notice] 33#33: gracefully shutting down
2022/12/28 18:28:00 [notice] 31#31: exiting
2022/12/28 18:28:00 [notice] 30#30: exiting
2022/12/28 18:28:00 [notice] 33#33: exiting
2022/12/28 18:28:00 [notice] 29#29: exiting
2022/12/28 18:28:00 [notice] 36#36: gracefully shutting down
2022/12/28 18:28:00 [notice] 30#30: exit
2022/12/28 18:28:00 [notice] 33#33: exit
2022/12/28 18:28:00 [notice] 31#31: exit
2022/12/28 18:28:00 [notice] 29#29: exit
2022/12/28 18:28:00 [notice] 36#36: exiting
2022/12/28 18:28:00 [notice] 36#36: exit
2022/12/28 18:28:00 [notice] 34#34: gracefully shutting down
2022/12/28 18:28:00 [notice] 32#32: gracefully shutting down
2022/12/28 18:28:00 [notice] 34#34: exiting
2022/12/28 18:28:00 [notice] 32#32: exiting
2022/12/28 18:28:00 [notice] 34#34: exit
2022/12/28 18:28:00 [notice] 32#32: exit
2022/12/28 18:28:00 [notice] 35#35: gracefully shutting down
2022/12/28 18:28:00 [notice] 35#35: exiting
2022/12/28 18:28:00 [notice] 35#35: exit
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:28:00 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:28:00 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:28:00 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:28:00 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:28:00 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:28:00 [notice] 1#1: exit
2022/12/28 18:29:38 [notice] 1#1: using the "epoll" event method
2022/12/28 18:29:38 [notice] 1#1: nginx/1.23.3
2022/12/28 18:29:38 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:29:38 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:29:38 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:29:38 [notice] 1#1: start worker processes
2022/12/28 18:29:38 [notice] 1#1: start worker process 29
2022/12/28 18:29:38 [notice] 1#1: start worker process 30
2022/12/28 18:29:38 [notice] 1#1: start worker process 31
2022/12/28 18:29:38 [notice] 1#1: start worker process 32
2022/12/28 18:29:38 [notice] 1#1: start worker process 33
2022/12/28 18:29:38 [notice] 1#1: start worker process 34
2022/12/28 18:29:38 [notice] 1#1: start worker process 35
2022/12/28 18:29:38 [notice] 1#1: start worker process 36
2022/12/28 18:29:45 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:29:47 [error] 29#29: *1 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:29:49 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:29:51 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:55 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:56 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:56 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:56 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:56 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:57 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:57 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:29:59 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:30:11 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:30:11 [notice] 29#29: gracefully shutting down
2022/12/28 18:30:11 [notice] 31#31: gracefully shutting down
2022/12/28 18:30:11 [notice] 30#30: gracefully shutting down
2022/12/28 18:30:11 [notice] 32#32: gracefully shutting down
2022/12/28 18:30:11 [notice] 35#35: gracefully shutting down
2022/12/28 18:30:11 [notice] 31#31: exiting
2022/12/28 18:30:11 [notice] 33#33: gracefully shutting down
2022/12/28 18:30:11 [notice] 29#29: exiting
2022/12/28 18:30:11 [notice] 30#30: exiting
2022/12/28 18:30:11 [notice] 35#35: exiting
2022/12/28 18:30:11 [notice] 32#32: exiting
2022/12/28 18:30:11 [notice] 31#31: exit
2022/12/28 18:30:11 [notice] 33#33: exiting
2022/12/28 18:30:11 [notice] 29#29: exit
2022/12/28 18:30:11 [notice] 30#30: exit
2022/12/28 18:30:11 [notice] 32#32: exit
2022/12/28 18:30:11 [notice] 35#35: exit
2022/12/28 18:30:11 [notice] 33#33: exit
2022/12/28 18:30:11 [notice] 34#34: gracefully shutting down
2022/12/28 18:30:11 [notice] 34#34: exiting
2022/12/28 18:30:11 [notice] 36#36: gracefully shutting down
2022/12/28 18:30:11 [notice] 34#34: exit
2022/12/28 18:30:11 [notice] 36#36: exiting
2022/12/28 18:30:11 [notice] 36#36: exit
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 18:30:11 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:30:11 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:30:11 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:30:11 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:30:11 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:30:11 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:30:11 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:30:11 [notice] 1#1: exit
2022/12/28 18:31:34 [notice] 1#1: using the "epoll" event method
2022/12/28 18:31:34 [notice] 1#1: nginx/1.23.3
2022/12/28 18:31:34 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:31:34 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:31:34 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:31:34 [notice] 1#1: start worker processes
2022/12/28 18:31:34 [notice] 1#1: start worker process 29
2022/12/28 18:31:34 [notice] 1#1: start worker process 30
2022/12/28 18:31:34 [notice] 1#1: start worker process 31
2022/12/28 18:31:34 [notice] 1#1: start worker process 32
2022/12/28 18:31:34 [notice] 1#1: start worker process 33
2022/12/28 18:31:34 [notice] 1#1: start worker process 34
2022/12/28 18:31:34 [notice] 1#1: start worker process 35
2022/12/28 18:31:34 [notice] 1#1: start worker process 36
2022/12/28 18:31:34 [error] 29#29: *1 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:35 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:35 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:36 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:36 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:36 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:36 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:36 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:37 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:37 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:37 [error] 30#30: *2 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:31:39 [error] 30#30: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:31:43 [error] 30#30: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET /?asdasd HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:31:45 [error] 30#30: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET /?foo HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:31:48 [error] 30#30: *2 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:31:50 [error] 30#30: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:42:39 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:42:39 [notice] 29#29: gracefully shutting down
2022/12/28 18:42:39 [notice] 31#31: gracefully shutting down
2022/12/28 18:42:39 [notice] 30#30: gracefully shutting down
2022/12/28 18:42:39 [notice] 33#33: gracefully shutting down
2022/12/28 18:42:39 [notice] 35#35: gracefully shutting down
2022/12/28 18:42:39 [notice] 32#32: gracefully shutting down
2022/12/28 18:42:39 [notice] 29#29: exiting
2022/12/28 18:42:39 [notice] 31#31: exiting
2022/12/28 18:42:39 [notice] 33#33: exiting
2022/12/28 18:42:39 [notice] 30#30: exiting
2022/12/28 18:42:39 [notice] 35#35: exiting
2022/12/28 18:42:39 [notice] 32#32: exiting
2022/12/28 18:42:39 [notice] 36#36: gracefully shutting down
2022/12/28 18:42:39 [notice] 34#34: gracefully shutting down
2022/12/28 18:42:39 [notice] 36#36: exiting
2022/12/28 18:42:39 [notice] 34#34: exiting
2022/12/28 18:42:39 [notice] 35#35: exit
2022/12/28 18:42:39 [notice] 33#33: exit
2022/12/28 18:42:39 [notice] 36#36: exit
2022/12/28 18:42:39 [notice] 32#32: exit
2022/12/28 18:42:39 [notice] 31#31: exit
2022/12/28 18:42:39 [notice] 34#34: exit
2022/12/28 18:42:39 [notice] 30#30: exit
2022/12/28 18:42:39 [notice] 29#29: exit
2022/12/28 18:42:39 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 18:42:39 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:42:39 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 18:42:39 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:42:39 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:42:39 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:42:39 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:42:39 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:42:39 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:42:39 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:42:39 [notice] 1#1: exit
2022/12/28 18:42:42 [notice] 1#1: using the "epoll" event method
2022/12/28 18:42:42 [notice] 1#1: nginx/1.23.3
2022/12/28 18:42:42 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:42:42 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:42:42 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:42:42 [notice] 1#1: start worker processes
2022/12/28 18:42:42 [notice] 1#1: start worker process 29
2022/12/28 18:42:42 [notice] 1#1: start worker process 30
2022/12/28 18:42:42 [notice] 1#1: start worker process 31
2022/12/28 18:42:42 [notice] 1#1: start worker process 32
2022/12/28 18:42:42 [notice] 1#1: start worker process 33
2022/12/28 18:42:42 [notice] 1#1: start worker process 34
2022/12/28 18:42:42 [notice] 1#1: start worker process 35
2022/12/28 18:42:42 [notice] 1#1: start worker process 36
2022/12/28 18:42:50 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:42:50 [notice] 29#29: gracefully shutting down
2022/12/28 18:42:50 [notice] 30#30: gracefully shutting down
2022/12/28 18:42:50 [notice] 31#31: gracefully shutting down
2022/12/28 18:42:50 [notice] 34#34: gracefully shutting down
2022/12/28 18:42:50 [notice] 36#36: gracefully shutting down
2022/12/28 18:42:50 [notice] 29#29: exiting
2022/12/28 18:42:50 [notice] 33#33: gracefully shutting down
2022/12/28 18:42:50 [notice] 30#30: exiting
2022/12/28 18:42:50 [notice] 31#31: exiting
2022/12/28 18:42:50 [notice] 34#34: exiting
2022/12/28 18:42:50 [notice] 36#36: exiting
2022/12/28 18:42:50 [notice] 33#33: exiting
2022/12/28 18:42:50 [notice] 30#30: exit
2022/12/28 18:42:50 [notice] 29#29: exit
2022/12/28 18:42:50 [notice] 36#36: exit
2022/12/28 18:42:50 [notice] 31#31: exit
2022/12/28 18:42:50 [notice] 33#33: exit
2022/12/28 18:42:50 [notice] 34#34: exit
2022/12/28 18:42:50 [notice] 35#35: gracefully shutting down
2022/12/28 18:42:50 [notice] 32#32: gracefully shutting down
2022/12/28 18:42:50 [notice] 35#35: exiting
2022/12/28 18:42:50 [notice] 32#32: exiting
2022/12/28 18:42:50 [notice] 35#35: exit
2022/12/28 18:42:50 [notice] 32#32: exit
2022/12/28 18:42:50 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:42:50 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:42:50 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:42:50 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:42:50 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:42:50 [notice] 1#1: exit
2022/12/28 18:42:52 [notice] 1#1: using the "epoll" event method
2022/12/28 18:42:52 [notice] 1#1: nginx/1.23.3
2022/12/28 18:42:52 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:42:52 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:42:52 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:42:52 [notice] 1#1: start worker processes
2022/12/28 18:42:52 [notice] 1#1: start worker process 29
2022/12/28 18:42:52 [notice] 1#1: start worker process 30
2022/12/28 18:42:52 [notice] 1#1: start worker process 31
2022/12/28 18:42:52 [notice] 1#1: start worker process 32
2022/12/28 18:42:52 [notice] 1#1: start worker process 33
2022/12/28 18:42:52 [notice] 1#1: start worker process 34
2022/12/28 18:42:52 [notice] 1#1: start worker process 35
2022/12/28 18:42:52 [notice] 1#1: start worker process 36
2022/12/28 18:42:57 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:43:00 [error] 29#29: *1 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:43:02 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:44:45 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:44:45 [notice] 29#29: gracefully shutting down
2022/12/28 18:44:45 [notice] 31#31: gracefully shutting down
2022/12/28 18:44:45 [notice] 32#32: gracefully shutting down
2022/12/28 18:44:45 [notice] 33#33: gracefully shutting down
2022/12/28 18:44:45 [notice] 36#36: gracefully shutting down
2022/12/28 18:44:45 [notice] 29#29: exiting
2022/12/28 18:44:45 [notice] 32#32: exiting
2022/12/28 18:44:45 [notice] 31#31: exiting
2022/12/28 18:44:45 [notice] 30#30: gracefully shutting down
2022/12/28 18:44:45 [notice] 33#33: exiting
2022/12/28 18:44:45 [notice] 36#36: exiting
2022/12/28 18:44:45 [notice] 30#30: exiting
2022/12/28 18:44:45 [notice] 31#31: exit
2022/12/28 18:44:45 [notice] 29#29: exit
2022/12/28 18:44:45 [notice] 32#32: exit
2022/12/28 18:44:45 [notice] 33#33: exit
2022/12/28 18:44:45 [notice] 36#36: exit
2022/12/28 18:44:45 [notice] 30#30: exit
2022/12/28 18:44:45 [notice] 34#34: gracefully shutting down
2022/12/28 18:44:45 [notice] 34#34: exiting
2022/12/28 18:44:45 [notice] 35#35: gracefully shutting down
2022/12/28 18:44:45 [notice] 35#35: exiting
2022/12/28 18:44:45 [notice] 34#34: exit
2022/12/28 18:44:45 [notice] 35#35: exit
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:44:45 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 18:44:45 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:44:45 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:44:45 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:44:45 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 18:44:45 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:44:45 [notice] 1#1: exit
2022/12/28 18:44:48 [notice] 1#1: using the "epoll" event method
2022/12/28 18:44:48 [notice] 1#1: nginx/1.23.3
2022/12/28 18:44:48 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:44:48 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:44:48 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:44:48 [notice] 1#1: start worker processes
2022/12/28 18:44:48 [notice] 1#1: start worker process 29
2022/12/28 18:44:48 [notice] 1#1: start worker process 30
2022/12/28 18:44:48 [notice] 1#1: start worker process 31
2022/12/28 18:44:48 [notice] 1#1: start worker process 32
2022/12/28 18:44:48 [notice] 1#1: start worker process 33
2022/12/28 18:44:48 [notice] 1#1: start worker process 34
2022/12/28 18:44:48 [notice] 1#1: start worker process 35
2022/12/28 18:44:48 [notice] 1#1: start worker process 36
2022/12/28 18:44:50 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:44:51 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:44:53 [error] 29#29: *1 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.128.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:44:55 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.2:9000", host: "localhost"
2022/12/28 18:44:57 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:44:57 [notice] 30#30: gracefully shutting down
2022/12/28 18:44:57 [notice] 32#32: gracefully shutting down
2022/12/28 18:44:57 [notice] 35#35: gracefully shutting down
2022/12/28 18:44:57 [notice] 30#30: exiting
2022/12/28 18:44:57 [notice] 31#31: gracefully shutting down
2022/12/28 18:44:57 [notice] 32#32: exiting
2022/12/28 18:44:57 [notice] 35#35: exiting
2022/12/28 18:44:57 [notice] 31#31: exiting
2022/12/28 18:44:57 [notice] 30#30: exit
2022/12/28 18:44:57 [notice] 32#32: exit
2022/12/28 18:44:57 [notice] 35#35: exit
2022/12/28 18:44:57 [notice] 31#31: exit
2022/12/28 18:44:57 [notice] 29#29: gracefully shutting down
2022/12/28 18:44:57 [notice] 34#34: gracefully shutting down
2022/12/28 18:44:57 [notice] 33#33: gracefully shutting down
2022/12/28 18:44:57 [notice] 34#34: exiting
2022/12/28 18:44:57 [notice] 36#36: gracefully shutting down
2022/12/28 18:44:57 [notice] 33#33: exiting
2022/12/28 18:44:57 [notice] 36#36: exiting
2022/12/28 18:44:57 [notice] 29#29: exiting
2022/12/28 18:44:57 [notice] 34#34: exit
2022/12/28 18:44:57 [notice] 33#33: exit
2022/12/28 18:44:57 [notice] 36#36: exit
2022/12/28 18:44:57 [notice] 29#29: exit
2022/12/28 18:44:57 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:44:57 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:57 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:44:57 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:57 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:44:57 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:44:57 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:44:57 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:44:57 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:44:57 [notice] 1#1: exit
2022/12/28 18:45:11 [notice] 1#1: using the "epoll" event method
2022/12/28 18:45:11 [notice] 1#1: nginx/1.23.3
2022/12/28 18:45:11 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:45:11 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:45:11 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:45:11 [notice] 1#1: start worker processes
2022/12/28 18:45:11 [notice] 1#1: start worker process 29
2022/12/28 18:45:11 [notice] 1#1: start worker process 30
2022/12/28 18:45:11 [notice] 1#1: start worker process 31
2022/12/28 18:45:11 [notice] 1#1: start worker process 32
2022/12/28 18:45:11 [notice] 1#1: start worker process 33
2022/12/28 18:45:11 [notice] 1#1: start worker process 34
2022/12/28 18:45:11 [notice] 1#1: start worker process 35
2022/12/28 18:45:11 [notice] 1#1: start worker process 36
2022/12/28 18:45:12 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.144.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.144.2:9000", host: "localhost"
2022/12/28 18:45:13 [error] 30#30: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.144.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.144.2:9000", host: "localhost"
2022/12/28 18:45:14 [error] 30#30: *3 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.144.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:45:16 [error] 30#30: *3 open() "/var/www/html/x" failed (2: No such file or directory), client: 192.168.144.1, server: , request: "GET /x HTTP/1.1", host: "localhost"
2022/12/28 18:45:21 [error] 30#30: *3 "/var/www/html/foo/index.php" is not found (2: No such file or directory), client: 192.168.144.1, server: , request: "GET /foo/ HTTP/1.1", host: "localhost"
2022/12/28 18:45:23 [error] 30#30: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.144.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.144.2:9000", host: "localhost"
2022/12/28 18:46:31 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:46:31 [notice] 29#29: gracefully shutting down
2022/12/28 18:46:31 [notice] 30#30: gracefully shutting down
2022/12/28 18:46:31 [notice] 31#31: gracefully shutting down
2022/12/28 18:46:31 [notice] 33#33: gracefully shutting down
2022/12/28 18:46:31 [notice] 36#36: gracefully shutting down
2022/12/28 18:46:31 [notice] 29#29: exiting
2022/12/28 18:46:31 [notice] 30#30: exiting
2022/12/28 18:46:31 [notice] 31#31: exiting
2022/12/28 18:46:31 [notice] 33#33: exiting
2022/12/28 18:46:31 [notice] 36#36: exiting
2022/12/28 18:46:31 [notice] 29#29: exit
2022/12/28 18:46:31 [notice] 30#30: exit
2022/12/28 18:46:31 [notice] 31#31: exit
2022/12/28 18:46:31 [notice] 33#33: exit
2022/12/28 18:46:31 [notice] 36#36: exit
2022/12/28 18:46:31 [notice] 32#32: gracefully shutting down
2022/12/28 18:46:31 [notice] 35#35: gracefully shutting down
2022/12/28 18:46:31 [notice] 34#34: gracefully shutting down
2022/12/28 18:46:31 [notice] 32#32: exiting
2022/12/28 18:46:31 [notice] 35#35: exiting
2022/12/28 18:46:31 [notice] 34#34: exiting
2022/12/28 18:46:31 [notice] 32#32: exit
2022/12/28 18:46:31 [notice] 35#35: exit
2022/12/28 18:46:31 [notice] 34#34: exit
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:46:32 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:46:32 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:46:32 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:46:32 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:46:32 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:46:32 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:46:32 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:46:32 [notice] 1#1: exit
2022/12/28 18:46:39 [notice] 1#1: using the "epoll" event method
2022/12/28 18:46:39 [notice] 1#1: nginx/1.23.3
2022/12/28 18:46:39 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:46:39 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:46:39 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:46:39 [notice] 1#1: start worker processes
2022/12/28 18:46:39 [notice] 1#1: start worker process 29
2022/12/28 18:46:39 [notice] 1#1: start worker process 30
2022/12/28 18:46:39 [notice] 1#1: start worker process 31
2022/12/28 18:46:39 [notice] 1#1: start worker process 32
2022/12/28 18:46:39 [notice] 1#1: start worker process 33
2022/12/28 18:46:39 [notice] 1#1: start worker process 34
2022/12/28 18:46:39 [notice] 1#1: start worker process 35
2022/12/28 18:46:39 [notice] 1#1: start worker process 36
2022/12/28 18:46:40 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:46:40 [error] 30#30: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:46:41 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:46:43 [error] 31#31: *5 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.160.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:46:45 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:50:15 [error] 32#32: *8 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:50:20 [error] 32#32: *8 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.160.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:50:24 [error] 32#32: *8 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.160.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:51:42 [error] 33#33: *10 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:53:57 [error] 34#34: *12 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.160.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.2:9000", host: "localhost"
2022/12/28 18:54:00 [error] 34#34: *12 open() "/var/www/html/foo" failed (2: No such file or directory), client: 192.168.160.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 18:58:03 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:58:03 [notice] 29#29: gracefully shutting down
2022/12/28 18:58:03 [notice] 30#30: gracefully shutting down
2022/12/28 18:58:03 [notice] 32#32: gracefully shutting down
2022/12/28 18:58:03 [notice] 33#33: gracefully shutting down
2022/12/28 18:58:03 [notice] 35#35: gracefully shutting down
2022/12/28 18:58:03 [notice] 29#29: exiting
2022/12/28 18:58:03 [notice] 30#30: exiting
2022/12/28 18:58:03 [notice] 33#33: exiting
2022/12/28 18:58:03 [notice] 32#32: exiting
2022/12/28 18:58:03 [notice] 35#35: exiting
2022/12/28 18:58:03 [notice] 29#29: exit
2022/12/28 18:58:03 [notice] 35#35: exit
2022/12/28 18:58:03 [notice] 30#30: exit
2022/12/28 18:58:03 [notice] 32#32: exit
2022/12/28 18:58:03 [notice] 33#33: exit
2022/12/28 18:58:03 [notice] 34#34: gracefully shutting down
2022/12/28 18:58:03 [notice] 31#31: gracefully shutting down
2022/12/28 18:58:03 [notice] 36#36: gracefully shutting down
2022/12/28 18:58:03 [notice] 34#34: exiting
2022/12/28 18:58:03 [notice] 31#31: exiting
2022/12/28 18:58:03 [notice] 36#36: exiting
2022/12/28 18:58:03 [notice] 34#34: exit
2022/12/28 18:58:03 [notice] 31#31: exit
2022/12/28 18:58:03 [notice] 36#36: exit
2022/12/28 18:58:03 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:58:03 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:03 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 18:58:03 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:03 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:58:03 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:03 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:58:03 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:03 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:58:03 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:58:03 [notice] 1#1: exit
2022/12/28 18:58:32 [notice] 1#1: using the "epoll" event method
2022/12/28 18:58:32 [notice] 1#1: nginx/1.23.3
2022/12/28 18:58:32 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 18:58:32 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 18:58:32 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 18:58:32 [notice] 1#1: start worker processes
2022/12/28 18:58:32 [notice] 1#1: start worker process 29
2022/12/28 18:58:32 [notice] 1#1: start worker process 30
2022/12/28 18:58:32 [notice] 1#1: start worker process 31
2022/12/28 18:58:32 [notice] 1#1: start worker process 32
2022/12/28 18:58:32 [notice] 1#1: start worker process 33
2022/12/28 18:58:32 [notice] 1#1: start worker process 34
2022/12/28 18:58:32 [notice] 1#1: start worker process 35
2022/12/28 18:58:32 [notice] 1#1: start worker process 36
2022/12/28 18:58:53 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 18:58:53 [notice] 30#30: gracefully shutting down
2022/12/28 18:58:53 [notice] 29#29: gracefully shutting down
2022/12/28 18:58:53 [notice] 32#32: gracefully shutting down
2022/12/28 18:58:53 [notice] 34#34: gracefully shutting down
2022/12/28 18:58:53 [notice] 31#31: gracefully shutting down
2022/12/28 18:58:53 [notice] 30#30: exiting
2022/12/28 18:58:53 [notice] 29#29: exiting
2022/12/28 18:58:53 [notice] 32#32: exiting
2022/12/28 18:58:53 [notice] 34#34: exiting
2022/12/28 18:58:53 [notice] 31#31: exiting
2022/12/28 18:58:53 [notice] 29#29: exit
2022/12/28 18:58:53 [notice] 30#30: exit
2022/12/28 18:58:53 [notice] 32#32: exit
2022/12/28 18:58:53 [notice] 34#34: exit
2022/12/28 18:58:53 [notice] 31#31: exit
2022/12/28 18:58:53 [notice] 35#35: gracefully shutting down
2022/12/28 18:58:53 [notice] 33#33: gracefully shutting down
2022/12/28 18:58:53 [notice] 36#36: gracefully shutting down
2022/12/28 18:58:53 [notice] 35#35: exiting
2022/12/28 18:58:53 [notice] 33#33: exiting
2022/12/28 18:58:53 [notice] 36#36: exiting
2022/12/28 18:58:53 [notice] 35#35: exit
2022/12/28 18:58:53 [notice] 33#33: exit
2022/12/28 18:58:53 [notice] 36#36: exit
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 18:58:53 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 18:58:53 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 18:58:53 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 18:58:53 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 18:58:53 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 18:58:53 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 18:58:53 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 18:58:53 [notice] 1#1: exit
2022/12/28 18:59:13 [emerg] 1#1: invalid variable name "/index.php" in /etc/nginx/conf.d/default.conf:11
2022/12/28 18:59:48 [emerg] 1#1: invalid variable name "index.php" in /etc/nginx/conf.d/default.conf:11
2022/12/28 19:00:40 [emerg] 1#1: invalid variable name "index.php" in /etc/nginx/conf.d/default.conf:11
2022/12/28 19:00:48 [emerg] 1#1: invalid variable name "index.php" in /etc/nginx/conf.d/default.conf:11
2022/12/28 19:01:43 [emerg] 1#1: invalid variable name "index.php" in /etc/nginx/conf.d/default.conf:7
2022/12/28 19:02:15 [notice] 1#1: using the "epoll" event method
2022/12/28 19:02:15 [notice] 1#1: nginx/1.23.3
2022/12/28 19:02:15 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:02:15 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:02:15 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:02:15 [notice] 1#1: start worker processes
2022/12/28 19:02:15 [notice] 1#1: start worker process 28
2022/12/28 19:02:15 [notice] 1#1: start worker process 29
2022/12/28 19:02:15 [notice] 1#1: start worker process 30
2022/12/28 19:02:15 [notice] 1#1: start worker process 31
2022/12/28 19:02:15 [notice] 1#1: start worker process 32
2022/12/28 19:02:15 [notice] 1#1: start worker process 33
2022/12/28 19:02:15 [notice] 1#1: start worker process 34
2022/12/28 19:02:15 [notice] 1#1: start worker process 35
2022/12/28 19:02:23 [error] 28#28: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.192.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.192.2:9000", host: "localhost"
2022/12/28 19:02:26 [error] 28#28: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:02:28 [error] 28#28: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:02:29 [error] 28#28: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:02:31 [error] 28#28: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.192.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.192.2:9000", host: "localhost"
2022/12/28 19:02:35 [error] 28#28: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:02:39 [error] 28#28: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:02:50 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:02:50 [notice] 28#28: gracefully shutting down
2022/12/28 19:02:50 [notice] 29#29: gracefully shutting down
2022/12/28 19:02:50 [notice] 33#33: gracefully shutting down
2022/12/28 19:02:50 [notice] 30#30: gracefully shutting down
2022/12/28 19:02:50 [notice] 29#29: exiting
2022/12/28 19:02:50 [notice] 33#33: exiting
2022/12/28 19:02:50 [notice] 30#30: exiting
2022/12/28 19:02:50 [notice] 28#28: exiting
2022/12/28 19:02:50 [notice] 29#29: exit
2022/12/28 19:02:50 [notice] 30#30: exit
2022/12/28 19:02:50 [notice] 33#33: exit
2022/12/28 19:02:50 [notice] 28#28: exit
2022/12/28 19:02:50 [notice] 32#32: gracefully shutting down
2022/12/28 19:02:50 [notice] 35#35: gracefully shutting down
2022/12/28 19:02:50 [notice] 32#32: exiting
2022/12/28 19:02:50 [notice] 35#35: exiting
2022/12/28 19:02:50 [notice] 32#32: exit
2022/12/28 19:02:50 [notice] 35#35: exit
2022/12/28 19:02:50 [notice] 34#34: gracefully shutting down
2022/12/28 19:02:50 [notice] 34#34: exiting
2022/12/28 19:02:50 [notice] 34#34: exit
2022/12/28 19:02:50 [notice] 31#31: gracefully shutting down
2022/12/28 19:02:50 [notice] 31#31: exiting
2022/12/28 19:02:50 [notice] 31#31: exit
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 19:02:50 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 19:02:50 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:02:50 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:02:50 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 28
2022/12/28 19:02:50 [notice] 1#1: worker process 28 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:02:50 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:02:50 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:02:50 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:02:50 [notice] 1#1: exit
2022/12/28 19:02:55 [notice] 1#1: using the "epoll" event method
2022/12/28 19:02:55 [notice] 1#1: nginx/1.23.3
2022/12/28 19:02:55 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:02:55 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:02:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:02:55 [notice] 1#1: start worker processes
2022/12/28 19:02:55 [notice] 1#1: start worker process 29
2022/12/28 19:02:55 [notice] 1#1: start worker process 30
2022/12/28 19:02:55 [notice] 1#1: start worker process 31
2022/12/28 19:02:55 [notice] 1#1: start worker process 32
2022/12/28 19:02:55 [notice] 1#1: start worker process 33
2022/12/28 19:02:55 [notice] 1#1: start worker process 34
2022/12/28 19:02:55 [notice] 1#1: start worker process 35
2022/12/28 19:02:55 [notice] 1#1: start worker process 36
2022/12/28 19:03:03 [error] 29#29: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:03:04 [error] 29#29: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.192.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:03:06 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:03:06 [notice] 30#30: gracefully shutting down
2022/12/28 19:03:06 [notice] 31#31: gracefully shutting down
2022/12/28 19:03:06 [notice] 35#35: gracefully shutting down
2022/12/28 19:03:06 [notice] 33#33: gracefully shutting down
2022/12/28 19:03:06 [notice] 29#29: gracefully shutting down
2022/12/28 19:03:06 [notice] 36#36: gracefully shutting down
2022/12/28 19:03:06 [notice] 30#30: exiting
2022/12/28 19:03:06 [notice] 31#31: exiting
2022/12/28 19:03:06 [notice] 35#35: exiting
2022/12/28 19:03:06 [notice] 33#33: exiting
2022/12/28 19:03:06 [notice] 36#36: exiting
2022/12/28 19:03:06 [notice] 29#29: exiting
2022/12/28 19:03:06 [notice] 35#35: exit
2022/12/28 19:03:06 [notice] 30#30: exit
2022/12/28 19:03:06 [notice] 31#31: exit
2022/12/28 19:03:06 [notice] 33#33: exit
2022/12/28 19:03:06 [notice] 36#36: exit
2022/12/28 19:03:06 [notice] 29#29: exit
2022/12/28 19:03:06 [notice] 34#34: gracefully shutting down
2022/12/28 19:03:06 [notice] 32#32: gracefully shutting down
2022/12/28 19:03:06 [notice] 34#34: exiting
2022/12/28 19:03:06 [notice] 32#32: exiting
2022/12/28 19:03:06 [notice] 34#34: exit
2022/12/28 19:03:06 [notice] 32#32: exit
2022/12/28 19:03:06 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 19:03:06 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:03:06 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 19:03:06 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:03:06 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:03:06 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:03:06 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:03:06 [notice] 1#1: exit
2022/12/28 19:03:18 [notice] 1#1: using the "epoll" event method
2022/12/28 19:03:18 [notice] 1#1: nginx/1.23.3
2022/12/28 19:03:18 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:03:18 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:03:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:03:18 [notice] 1#1: start worker processes
2022/12/28 19:03:18 [notice] 1#1: start worker process 29
2022/12/28 19:03:18 [notice] 1#1: start worker process 30
2022/12/28 19:03:18 [notice] 1#1: start worker process 31
2022/12/28 19:03:18 [notice] 1#1: start worker process 32
2022/12/28 19:03:18 [notice] 1#1: start worker process 33
2022/12/28 19:03:18 [notice] 1#1: start worker process 34
2022/12/28 19:03:18 [notice] 1#1: start worker process 35
2022/12/28 19:03:18 [notice] 1#1: start worker process 36
2022/12/28 19:06:18 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:06:18 [notice] 29#29: gracefully shutting down
2022/12/28 19:06:18 [notice] 30#30: gracefully shutting down
2022/12/28 19:06:18 [notice] 31#31: gracefully shutting down
2022/12/28 19:06:18 [notice] 33#33: gracefully shutting down
2022/12/28 19:06:18 [notice] 32#32: gracefully shutting down
2022/12/28 19:06:18 [notice] 35#35: gracefully shutting down
2022/12/28 19:06:18 [notice] 34#34: gracefully shutting down
2022/12/28 19:06:18 [notice] 32#32: exiting
2022/12/28 19:06:18 [notice] 36#36: gracefully shutting down
2022/12/28 19:06:18 [notice] 35#35: exiting
2022/12/28 19:06:18 [notice] 29#29: exiting
2022/12/28 19:06:18 [notice] 34#34: exiting
2022/12/28 19:06:18 [notice] 33#33: exiting
2022/12/28 19:06:18 [notice] 31#31: exiting
2022/12/28 19:06:18 [notice] 36#36: exiting
2022/12/28 19:06:18 [notice] 30#30: exiting
2022/12/28 19:06:18 [notice] 32#32: exit
2022/12/28 19:06:18 [notice] 29#29: exit
2022/12/28 19:06:18 [notice] 34#34: exit
2022/12/28 19:06:18 [notice] 36#36: exit
2022/12/28 19:06:18 [notice] 35#35: exit
2022/12/28 19:06:18 [notice] 31#31: exit
2022/12/28 19:06:18 [notice] 33#33: exit
2022/12/28 19:06:18 [notice] 30#30: exit
2022/12/28 19:06:18 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 19:06:18 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:06:18 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:06:18 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:06:18 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:06:18 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:06:18 [notice] 1#1: exit
2022/12/28 19:06:31 [notice] 1#1: using the "epoll" event method
2022/12/28 19:06:31 [notice] 1#1: nginx/1.23.3
2022/12/28 19:06:31 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:06:31 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:06:31 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:06:31 [notice] 1#1: start worker processes
2022/12/28 19:06:31 [notice] 1#1: start worker process 29
2022/12/28 19:06:31 [notice] 1#1: start worker process 30
2022/12/28 19:06:31 [notice] 1#1: start worker process 31
2022/12/28 19:06:31 [notice] 1#1: start worker process 32
2022/12/28 19:06:31 [notice] 1#1: start worker process 33
2022/12/28 19:06:31 [notice] 1#1: start worker process 34
2022/12/28 19:06:31 [notice] 1#1: start worker process 35
2022/12/28 19:06:31 [notice] 1#1: start worker process 36
2022/12/28 19:06:45 [error] 29#29: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.208.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:06:49 [error] 29#29: *1 open() "/var/www/site/foo" failed (2: No such file or directory), client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", host: "localhost"
2022/12/28 19:06:51 [error] 29#29: *1 "/var/www/site/index.php" is not found (2: No such file or directory), client: 192.168.208.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2022/12/28 19:09:40 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:09:40 [notice] 29#29: gracefully shutting down
2022/12/28 19:09:40 [notice] 29#29: exiting
2022/12/28 19:09:40 [notice] 31#31: gracefully shutting down
2022/12/28 19:09:40 [notice] 32#32: gracefully shutting down
2022/12/28 19:09:40 [notice] 33#33: gracefully shutting down
2022/12/28 19:09:40 [notice] 35#35: gracefully shutting down
2022/12/28 19:09:40 [notice] 30#30: gracefully shutting down
2022/12/28 19:09:40 [notice] 31#31: exiting
2022/12/28 19:09:40 [notice] 32#32: exiting
2022/12/28 19:09:40 [notice] 35#35: exiting
2022/12/28 19:09:40 [notice] 30#30: exiting
2022/12/28 19:09:40 [notice] 29#29: exit
2022/12/28 19:09:40 [notice] 32#32: exit
2022/12/28 19:09:40 [notice] 31#31: exit
2022/12/28 19:09:40 [notice] 30#30: exit
2022/12/28 19:09:40 [notice] 35#35: exit
2022/12/28 19:09:40 [notice] 33#33: exiting
2022/12/28 19:09:40 [notice] 34#34: gracefully shutting down
2022/12/28 19:09:40 [notice] 34#34: exiting
2022/12/28 19:09:40 [notice] 36#36: gracefully shutting down
2022/12/28 19:09:40 [notice] 33#33: exit
2022/12/28 19:09:40 [notice] 36#36: exiting
2022/12/28 19:09:40 [notice] 34#34: exit
2022/12/28 19:09:40 [notice] 36#36: exit
2022/12/28 19:09:40 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:09:40 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:09:40 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:09:40 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 19:09:40 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:09:40 [notice] 1#1: exit
2022/12/28 19:09:48 [notice] 1#1: using the "epoll" event method
2022/12/28 19:09:48 [notice] 1#1: nginx/1.23.3
2022/12/28 19:09:48 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:09:48 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:09:48 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:09:48 [notice] 1#1: start worker processes
2022/12/28 19:09:48 [notice] 1#1: start worker process 29
2022/12/28 19:09:48 [notice] 1#1: start worker process 30
2022/12/28 19:09:48 [notice] 1#1: start worker process 31
2022/12/28 19:09:48 [notice] 1#1: start worker process 32
2022/12/28 19:09:48 [notice] 1#1: start worker process 33
2022/12/28 19:09:48 [notice] 1#1: start worker process 34
2022/12/28 19:09:48 [notice] 1#1: start worker process 35
2022/12/28 19:09:48 [notice] 1#1: start worker process 36
2022/12/28 19:09:52 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:09:54 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:09:56 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:02 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:05 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:41 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:10:41 [notice] 30#30: gracefully shutting down
2022/12/28 19:10:41 [notice] 32#32: gracefully shutting down
2022/12/28 19:10:41 [notice] 35#35: gracefully shutting down
2022/12/28 19:10:41 [notice] 32#32: exiting
2022/12/28 19:10:41 [notice] 30#30: exiting
2022/12/28 19:10:41 [notice] 35#35: exiting
2022/12/28 19:10:41 [notice] 32#32: exit
2022/12/28 19:10:41 [notice] 30#30: exit
2022/12/28 19:10:41 [notice] 35#35: exit
2022/12/28 19:10:41 [notice] 29#29: gracefully shutting down
2022/12/28 19:10:41 [notice] 31#31: gracefully shutting down
2022/12/28 19:10:41 [notice] 34#34: gracefully shutting down
2022/12/28 19:10:41 [notice] 29#29: exiting
2022/12/28 19:10:41 [notice] 31#31: exiting
2022/12/28 19:10:41 [notice] 34#34: exiting
2022/12/28 19:10:41 [notice] 29#29: exit
2022/12/28 19:10:41 [notice] 31#31: exit
2022/12/28 19:10:41 [notice] 34#34: exit
2022/12/28 19:10:41 [notice] 36#36: gracefully shutting down
2022/12/28 19:10:41 [notice] 36#36: exiting
2022/12/28 19:10:41 [notice] 36#36: exit
2022/12/28 19:10:41 [notice] 33#33: gracefully shutting down
2022/12/28 19:10:41 [notice] 33#33: exiting
2022/12/28 19:10:41 [notice] 33#33: exit
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:10:41 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:10:41 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 19:10:41 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:10:41 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 19:10:41 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 19:10:41 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:10:41 [notice] 1#1: exit
2022/12/28 19:10:45 [notice] 1#1: using the "epoll" event method
2022/12/28 19:10:45 [notice] 1#1: nginx/1.23.3
2022/12/28 19:10:45 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:10:45 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:10:45 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:10:45 [notice] 1#1: start worker processes
2022/12/28 19:10:45 [notice] 1#1: start worker process 29
2022/12/28 19:10:45 [notice] 1#1: start worker process 30
2022/12/28 19:10:45 [notice] 1#1: start worker process 31
2022/12/28 19:10:45 [notice] 1#1: start worker process 32
2022/12/28 19:10:45 [notice] 1#1: start worker process 33
2022/12/28 19:10:45 [notice] 1#1: start worker process 34
2022/12/28 19:10:45 [notice] 1#1: start worker process 35
2022/12/28 19:10:45 [notice] 1#1: start worker process 36
2022/12/28 19:10:47 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:10:50 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:13 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:12:13 [notice] 30#30: gracefully shutting down
2022/12/28 19:12:13 [notice] 32#32: gracefully shutting down
2022/12/28 19:12:13 [notice] 30#30: exiting
2022/12/28 19:12:13 [notice] 32#32: exiting
2022/12/28 19:12:13 [notice] 30#30: exit
2022/12/28 19:12:13 [notice] 32#32: exit
2022/12/28 19:12:13 [notice] 29#29: gracefully shutting down
2022/12/28 19:12:13 [notice] 31#31: gracefully shutting down
2022/12/28 19:12:13 [notice] 29#29: exiting
2022/12/28 19:12:13 [notice] 31#31: exiting
2022/12/28 19:12:13 [notice] 36#36: gracefully shutting down
2022/12/28 19:12:13 [notice] 31#31: exit
2022/12/28 19:12:13 [notice] 36#36: exiting
2022/12/28 19:12:13 [notice] 29#29: exit
2022/12/28 19:12:13 [notice] 36#36: exit
2022/12/28 19:12:13 [notice] 34#34: gracefully shutting down
2022/12/28 19:12:13 [notice] 33#33: gracefully shutting down
2022/12/28 19:12:13 [notice] 34#34: exiting
2022/12/28 19:12:13 [notice] 33#33: exiting
2022/12/28 19:12:13 [notice] 34#34: exit
2022/12/28 19:12:13 [notice] 33#33: exit
2022/12/28 19:12:13 [notice] 35#35: gracefully shutting down
2022/12/28 19:12:13 [notice] 35#35: exiting
2022/12/28 19:12:13 [notice] 35#35: exit
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:12:13 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:12:13 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 31
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:12:13 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 19:12:13 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:12:13 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:12:13 [notice] 1#1: exit
2022/12/28 19:12:17 [notice] 1#1: using the "epoll" event method
2022/12/28 19:12:17 [notice] 1#1: nginx/1.23.3
2022/12/28 19:12:17 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:12:17 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:12:17 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:12:17 [notice] 1#1: start worker processes
2022/12/28 19:12:17 [notice] 1#1: start worker process 29
2022/12/28 19:12:17 [notice] 1#1: start worker process 30
2022/12/28 19:12:17 [notice] 1#1: start worker process 31
2022/12/28 19:12:17 [notice] 1#1: start worker process 32
2022/12/28 19:12:17 [notice] 1#1: start worker process 33
2022/12/28 19:12:17 [notice] 1#1: start worker process 34
2022/12/28 19:12:17 [notice] 1#1: start worker process 35
2022/12/28 19:12:17 [notice] 1#1: start worker process 36
2022/12/28 19:12:20 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:20 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:23 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:25 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:37 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:43 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:49 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /asdausdsasuduasd HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:12:51 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:13:03 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:13:03 [notice] 29#29: gracefully shutting down
2022/12/28 19:13:03 [notice] 30#30: gracefully shutting down
2022/12/28 19:13:03 [notice] 31#31: gracefully shutting down
2022/12/28 19:13:03 [notice] 33#33: gracefully shutting down
2022/12/28 19:13:03 [notice] 30#30: exiting
2022/12/28 19:13:03 [notice] 31#31: exiting
2022/12/28 19:13:03 [notice] 29#29: exiting
2022/12/28 19:13:03 [notice] 33#33: exiting
2022/12/28 19:13:03 [notice] 31#31: exit
2022/12/28 19:13:03 [notice] 29#29: exit
2022/12/28 19:13:03 [notice] 33#33: exit
2022/12/28 19:13:03 [notice] 30#30: exit
2022/12/28 19:13:03 [notice] 32#32: gracefully shutting down
2022/12/28 19:13:03 [notice] 32#32: exiting
2022/12/28 19:13:03 [notice] 34#34: gracefully shutting down
2022/12/28 19:13:03 [notice] 36#36: gracefully shutting down
2022/12/28 19:13:03 [notice] 34#34: exiting
2022/12/28 19:13:03 [notice] 36#36: exiting
2022/12/28 19:13:03 [notice] 32#32: exit
2022/12/28 19:13:03 [notice] 34#34: exit
2022/12/28 19:13:03 [notice] 36#36: exit
2022/12/28 19:13:03 [notice] 35#35: gracefully shutting down
2022/12/28 19:13:03 [notice] 35#35: exiting
2022/12/28 19:13:03 [notice] 35#35: exit
2022/12/28 19:13:04 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:13:04 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:04 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:13:04 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:13:04 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:04 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:13:04 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:04 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:13:04 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:13:04 [notice] 1#1: exit
2022/12/28 19:13:07 [notice] 1#1: using the "epoll" event method
2022/12/28 19:13:07 [notice] 1#1: nginx/1.23.3
2022/12/28 19:13:07 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:13:07 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:13:07 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:13:07 [notice] 1#1: start worker processes
2022/12/28 19:13:07 [notice] 1#1: start worker process 29
2022/12/28 19:13:07 [notice] 1#1: start worker process 30
2022/12/28 19:13:07 [notice] 1#1: start worker process 31
2022/12/28 19:13:07 [notice] 1#1: start worker process 32
2022/12/28 19:13:07 [notice] 1#1: start worker process 33
2022/12/28 19:13:07 [notice] 1#1: start worker process 34
2022/12/28 19:13:07 [notice] 1#1: start worker process 35
2022/12/28 19:13:07 [notice] 1#1: start worker process 36
2022/12/28 19:13:16 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:13:18 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:13:20 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.208.1, server: , request: "GET /asdhasd HTTP/1.1", upstream: "fastcgi://192.168.208.2:9000", host: "localhost"
2022/12/28 19:13:28 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:13:28 [notice] 30#30: gracefully shutting down
2022/12/28 19:13:28 [notice] 32#32: gracefully shutting down
2022/12/28 19:13:28 [notice] 35#35: gracefully shutting down
2022/12/28 19:13:28 [notice] 29#29: gracefully shutting down
2022/12/28 19:13:28 [notice] 30#30: exiting
2022/12/28 19:13:28 [notice] 32#32: exiting
2022/12/28 19:13:28 [notice] 35#35: exiting
2022/12/28 19:13:28 [notice] 29#29: exiting
2022/12/28 19:13:28 [notice] 30#30: exit
2022/12/28 19:13:28 [notice] 32#32: exit
2022/12/28 19:13:28 [notice] 35#35: exit
2022/12/28 19:13:28 [notice] 29#29: exit
2022/12/28 19:13:28 [notice] 31#31: gracefully shutting down
2022/12/28 19:13:28 [notice] 31#31: exiting
2022/12/28 19:13:28 [notice] 31#31: exit
2022/12/28 19:13:28 [notice] 33#33: gracefully shutting down
2022/12/28 19:13:28 [notice] 33#33: exiting
2022/12/28 19:13:28 [notice] 33#33: exit
2022/12/28 19:13:28 [notice] 34#34: gracefully shutting down
2022/12/28 19:13:28 [notice] 34#34: exiting
2022/12/28 19:13:28 [notice] 34#34: exit
2022/12/28 19:13:28 [notice] 36#36: gracefully shutting down
2022/12/28 19:13:28 [notice] 36#36: exiting
2022/12/28 19:13:28 [notice] 36#36: exit
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 30
2022/12/28 19:13:28 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:13:28 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:13:28 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2022/12/28 19:13:28 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 36
2022/12/28 19:13:28 [notice] 1#1: signal 17 (SIGCHLD) received from 32
2022/12/28 19:13:28 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:13:28 [notice] 1#1: exit
2022/12/28 19:13:44 [notice] 1#1: using the "epoll" event method
2022/12/28 19:13:44 [notice] 1#1: nginx/1.23.3
2022/12/28 19:13:44 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:13:44 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:13:44 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:13:44 [notice] 1#1: start worker processes
2022/12/28 19:13:44 [notice] 1#1: start worker process 29
2022/12/28 19:13:44 [notice] 1#1: start worker process 30
2022/12/28 19:13:44 [notice] 1#1: start worker process 31
2022/12/28 19:13:44 [notice] 1#1: start worker process 32
2022/12/28 19:13:44 [notice] 1#1: start worker process 33
2022/12/28 19:13:44 [notice] 1#1: start worker process 34
2022/12/28 19:13:44 [notice] 1#1: start worker process 35
2022/12/28 19:13:44 [notice] 1#1: start worker process 36
2022/12/28 19:13:46 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /asdhasd HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:13:47 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /asdhasd HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:13:47 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /asdhasd HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:13:48 [error] 29#29: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:13:54 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2022/12/28 19:13:54 [notice] 29#29: gracefully shutting down
2022/12/28 19:13:54 [notice] 31#31: gracefully shutting down
2022/12/28 19:13:54 [notice] 30#30: gracefully shutting down
2022/12/28 19:13:54 [notice] 31#31: exiting
2022/12/28 19:13:54 [notice] 30#30: exiting
2022/12/28 19:13:54 [notice] 29#29: exiting
2022/12/28 19:13:54 [notice] 31#31: exit
2022/12/28 19:13:54 [notice] 30#30: exit
2022/12/28 19:13:54 [notice] 29#29: exit
2022/12/28 19:13:54 [notice] 32#32: gracefully shutting down
2022/12/28 19:13:54 [notice] 34#34: gracefully shutting down
2022/12/28 19:13:54 [notice] 35#35: gracefully shutting down
2022/12/28 19:13:54 [notice] 33#33: gracefully shutting down
2022/12/28 19:13:54 [notice] 32#32: exiting
2022/12/28 19:13:54 [notice] 34#34: exiting
2022/12/28 19:13:54 [notice] 35#35: exiting
2022/12/28 19:13:54 [notice] 33#33: exiting
2022/12/28 19:13:54 [notice] 32#32: exit
2022/12/28 19:13:54 [notice] 34#34: exit
2022/12/28 19:13:54 [notice] 33#33: exit
2022/12/28 19:13:54 [notice] 35#35: exit
2022/12/28 19:13:54 [notice] 36#36: gracefully shutting down
2022/12/28 19:13:54 [notice] 36#36: exiting
2022/12/28 19:13:54 [notice] 36#36: exit
2022/12/28 19:13:54 [notice] 1#1: signal 17 (SIGCHLD) received from 34
2022/12/28 19:13:54 [notice] 1#1: worker process 30 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 31 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 32 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 33 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 34 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 35 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: worker process 36 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: signal 29 (SIGIO) received
2022/12/28 19:13:54 [notice] 1#1: signal 17 (SIGCHLD) received from 33
2022/12/28 19:13:54 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2022/12/28 19:13:54 [notice] 1#1: worker process 29 exited with code 0
2022/12/28 19:13:54 [notice] 1#1: exit
2022/12/28 19:13:58 [notice] 1#1: using the "epoll" event method
2022/12/28 19:13:58 [notice] 1#1: nginx/1.23.3
2022/12/28 19:13:58 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2022/12/28 19:13:58 [notice] 1#1: OS: Linux 5.15.0-56-generic
2022/12/28 19:13:58 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/12/28 19:13:58 [notice] 1#1: start worker processes
2022/12/28 19:13:58 [notice] 1#1: start worker process 29
2022/12/28 19:13:58 [notice] 1#1: start worker process 30
2022/12/28 19:13:58 [notice] 1#1: start worker process 31
2022/12/28 19:13:58 [notice] 1#1: start worker process 32
2022/12/28 19:13:58 [notice] 1#1: start worker process 33
2022/12/28 19:13:58 [notice] 1#1: start worker process 34
2022/12/28 19:13:58 [notice] 1#1: start worker process 35
2022/12/28 19:13:58 [notice] 1#1: start worker process 36
2022/12/28 19:14:01 [error] 29#29: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:29:36 [error] 30#30: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:31:37 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:31:38 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:36:12 [error] 32#32: *8 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:36:13 [error] 32#32: *8 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:38:44 [error] 33#33: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:38:45 [error] 33#33: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:38:56 [error] 33#33: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:40:13 [error] 34#34: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:45:40 [error] 35#35: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:45:43 [error] 35#35: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:45:46 [error] 35#35: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foox HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:45:48 [error] 35#35: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:50:08 [error] 36#36: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:50:55 [error] 36#36: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:51:49 [error] 36#36: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:51:54 [error] 36#36: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/28 19:51:57 [error] 36#36: *22 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:06:58 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:07:25 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:07:25 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:07:59 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:00 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:02 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:09 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:12 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:19 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:47 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:08:50 [error] 29#29: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:18:12 [error] 29#29: *40 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:18:46 [error] 29#29: *40 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:18:47 [error] 29#29: *40 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:19:19 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:19:36 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:19:36 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:19:36 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:31 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:49 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:50 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:50 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:50 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:20:58 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:03 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:11 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:12 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:12 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:13 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:14 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:15 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:15 [error] 29#29: *51 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:25 [error] 29#29: *70 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:21:25 [error] 29#29: *70 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost", referrer: "http://localhost/"
2022/12/29 12:25:57 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:25:59 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:26:05 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:26:08 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:26:19 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:26:20 [error] 29#29: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:19 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:21 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:32 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:38 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:40 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:42 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:44 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:50 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:29:51 [error] 29#29: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:31:09 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /foo HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:31:10 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET /bar HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:31:13 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:32:17 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:32:22 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:32:22 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
2022/12/29 12:32:23 [error] 29#29: *91 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.224.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.224.2:9000", host: "localhost"
